### ISSUE TITLE
Is possible to get additional information

### ISSUE THREAD

**Issue by dyanakiev** [cwarwicker/Waddle#1]
Hello, i need information for the type of sport/activity, how to get it?

**Comment by cwarwicker** [comment]
Do you mean just the title, like "Running" or "Cycling"?

**Comment by dyanakiev** [comment]
Yes

**Comment by dyanakiev** [comment]
@cwarwicker 
Im just testing now and i got this error spamming in my error log:
```
ERROR - 06.02.2018 10:56:10 --> Severity: 4096 --> Argument 1 passed to Waddle\Parsers\CSVParser::getHeaderKey() must be an instance of Waddle\Parsers\string, string given, called in /application/libraries/waddle/Parsers/CSVParser.php on line 51 and defined /application/libraries/waddle/Parsers/CSVParser.php 165
```

**Comment by cwarwicker** [comment]
Hi, sorry for the late reply. Can you remember what csv file you were using? I only ever tested this with my tomtom watch, so i suspect your device might be generating a different csv from mine. If you've still got it and can attach it, i'll see how it compares to what it's expecting.
