### ISSUE TITLE
Composer not cooperating with tags without "v"

### ISSUE THREAD

**Issue by briedis** [cwarwicker/Waddle#11]
When I tried updating the package with version `^1.0`, composer shows this:

```- The requested package duckfusion/waddle ^1.0 exists as duckfusion/waddle[dev-master] but these are rejected by your constraint.```

Apparently, Composer wants version names as "v1.0" and not "1.0".

We should probably drop the tag and create a new one.

I just tried releasing a "v1.0" tag on my fork and composer could install it without a problem.

**Comment by briedis** [comment]
Ping. This should be a 1 min fix :)

**Comment by cwarwicker** [comment]
This should be okay now for the v1.1 tag i just made.
