### ISSUE TITLE
Update composer package in packagist

### ISSUE THREAD

**Issue by ahoogerheide** [cwarwicker/Waddle#15]
It seems the v1.1 tag is not available in packagist, resulting in being unable to update using composer.

` - The requested package duckfusion/waddle ^1.1 exists as duckfusion/waddle[dev-master, dev-pr/10, v1.0] but these are rejected by your constraint.`

If I try to install dev-master I get an old commtit 02f1b2e6d9
Could you update the package in packagist?

**Comment by cwarwicker** [comment]
I realise I'm 4 years late, but I've done this now.
