### ISSUE TITLE
gpx more than 1 <trk>

### ISSUE THREAD

**Issue by parkstraat9** [cwarwicker/Waddle#16]
I have a gpx file that has more than 1 < trk > section. 
When I read that file with $activity->getTotalDistance()
I got only a part of the total distance. 
 
 Is there an option to read all < trk > segments at once? 
 
 example file:
[ https://www.dropbox.com/s/ovikbiex7ikp6zy/Grand%20TUHR.GPX?dl=1]( https://www.dropbox.com/s/ovikbiex7ikp6zy/Grand%20TUHR.GPX?dl=1)

**Comment by cwarwicker** [comment]
Hi,

I'm a bit confused by that file. It looks like the 2nd <trk> section contains elements from various different dates and times.
