### ISSUE TITLE
Reading Meta

### ISSUE THREAD

**Issue by slhuilli1** [cwarwicker/Waddle#18]
Hi, 
Great works  I use it since 2 days and it is a great work

You should add somme method for reading meta data of files. I have written some regex  (I can send you my regex for that)

Thanks

**Comment by cwarwicker** [comment]
I haven't done any work on this for years. Can you give me an example of what you want? Or feel free to open a PR if you've implemented the code yourself.

**Comment by slhuilli1** [comment]
Hi, 
if you look on the top of th file (look on my regex test : https://regex101.com/r/bBW7J0/1), you will see there are some metadatas for a GPX file (I don't have update your code, I have written theses regex for another project). I work with the website gpx.studio (it is the domain name) and I draw my maps on it, I download their generated files. So, I do not have control over the content of the file's meta datas.
Biut I have written 3 regex for extracting datas : 

- https://regex101.com/r/bBW7J0/1
- https://regex101.com/r/R5dhbz/1
- https://regex101.com/r/AHR0ba/1

I work with GPX file which have only these 3 méat datas but  when I read the GPX Format file documentation, I have seen the standard have more metadat to extract (https://www.topografix.com/GPX/1/1/#type_metadataType) If you read these standard, you will see 9 meta data : 
-name
-desc
-author
-copyright
-link
-time
-keywords
-bounds
-extensions

All are not fully usefuf for me but name, desc, author, and time are very useful for ordering GPX files when I upload it for public downloading.

I can copy-paste this comment as PR if you want.

NOTE : If you have somme problem to read my regex, say me

Thanks

**Comment by cwarwicker** [comment]
Ok, i'll have a look at doing it when i get a bit of downtime.

**Comment by cwarwicker** [comment]
I've added metadata to the GPXParser now if you can pull down latest changes.

You can access it from `$activity->getMetaData`.

Let me know if you need anyhting else.
