### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by demlak** [cwarwicker/Waddle#4]
Hi,
thx for this great parsers.

I'm interested in "real activity time".

`$activity->getTotalDuration()` does not reflect any breaks in activity.

Maybe it is possible to grep breaks to reflect real activity time. This should also affect average speed and calories, and so on.

Just an idea:
maybe by calculating speed between two points is somewhat below 5kph for biking and 2kph for walking, we got a break. 
Or by calculating time between two points that are x-metres in distance to each other.
(because some people track there activity with big intervals)

thx in advance

**Comment by cwarwicker** [comment]
Hi,

I'll have a look into it.

**Comment by dlondero** [comment]
This sounds like the "Moving time" compared to the "Elapsed time" some platforms provide (Strava does this). Most probably they check for track points with same coordinates (or within a certain range) and subtract the time spent in the same place from the total time (elapsed).
